version: "3"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # networks:
    #   - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/pi/heimdall/config:/config
    ports:
      - 8500:80
    #   - 8443:443
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=proxy"
    #   - "traefik.http.routers.heimdall.entrypoints=websecure"
    #   - "traefik.http.routers.heimdall.rule=Host(`abhijit.ddns.net`)"
    #   - "traefik.http.routers.heimdall.service=heimdall"
    #   - "traefik.http.routers.heimdall.tls.certresolver=production"
    #   - "traefik.http.services.heimdall.loadbalancer.server.port=8500"
    #   - "traefik.http.services.heimdall.loadbalancer.passhostheader=true"

# networks:
#   proxy:
#     external: true
