version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    ports:
      - 8081:80
    volumes:
      - /mnt/Expansion/:/srv
      - /mnt/Expansion/filebrowser/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true