# http:
#  #region routers 
#   routers:
#     # nginx:
#     #   entryPoints:
#     #     - "websecure"
#     #   rule: "Host(`abhijit.ddns.net`)"
#     #   tls:
#     #     certResolver: production
#     #   service: nginx

# #endregion
# #region services
#   services:
#     nginx:
#       loadBalancer:
#         servers:
#           - url: "https://192.168.0.132:5500"
#         passHostHeader: true
    
# #endregion
#   middlewares:
#     https-redirect:
#       redirectScheme:
#         scheme: https

#     default-headers:
#       headers:
#         frameDeny: true
#         sslRedirect: true
#         browserXssFilter: true
#         contentTypeNosniff: true
#         forceSTSHeader: true
#         stsIncludeSubdomains: true
#         stsPreload: true
#         stsSeconds: 15552000
#         customFrameOptionsValue: SAMEORIGIN
#         customRequestHeaders:
#           X-Forwarded-Proto: https

#     default-whitelist:
#       ipWhiteList:
#         sourceRange:
#         - "10.0.0.0/24"
#         - "192.168.0.0/24"

#     secured:
#       chain:
#         middlewares:
#         - default-whitelist
#         - default-headers