version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik:/etc/traefik
      - ./ssl-certs:/ssl-certs
      