version: '3'

services:
  traefik:
    image: traefik:v2.8
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/pi/pi-labs/traefik/config/traefik.yml:/traefik.yml:ro
      - /home/pi/pi-labs/traefik/ssl-certs/acme.json:/ssl-certs/acme.json


networks:
  proxy:
    external: true
