version: "3.8"

services:
  web:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    networks:
      - proxy
    ports:
      - "5500:80"
    volumes:
      - "/home/pi/pi-labs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/home/pi/pi-labs/nginx/app/:/app/"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nginx.rule=Host(`abhijit.ddns.net`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      # Redirect these routes to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nginx.middlewares=redirect-to-https@docker"      
      - "traefik.http.routers.nginx-secure.rule=Host(`abhijit.ddns.net`)"
      - "traefik.http.routers.nginx-secure.entrypoints=websecure"
      - "traefik.http.routers.nginx-secure.tls=true"
      - "traefik.http.routers.nginx-secure.tls.certresolver=production"

networks:
  proxy:
    external: true
