version: "3.8"

services:
  web:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./app/:/app/"
    restart: always
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.rule=Host(`abhijit.ddns.net`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=production"

networks:
  traefik_default:
    external: true